export const dataDB=[
    {
        id:1,
        name:"sofa verde",
        urlImages: "./images/sofa.jpg",
        stock:4,
        price:2.000,
    },
    {
        id:2,
        name:"sofa gris",
        urlImages: "./images/sofa-gris.jpg",
        stock:6,
        price:1.950,
    },
    {
        id:3,
        name:"silla deluxe",
        urlImages: "./images/silla-deluxe.jpg",
        stock:12,
        price:250,
    },
    {
        id:4,
        name:"silla de Cabecera",
        urlImages: "./images/silla-cabaecera.jpg",
        stock:12,   
        price:190,
    },
    {
        id:5,
        name:"repisas",
        urlImages: "./images/repisas.jpg",
        stock:15,
        price:30,
    },
    {
        id:6,
        name:"meza lateral",
        urlImages: "./images/meza-lateral.jpg",
        stock:8,
        price:45,
    },
    {
        id:7,
        name:"juego dormitorio",
        urlImages: "./images/Juego-dormitorio.jpg",
        stock:12,
        price:3.500,
    },
    {
        id:8,
        name:"comedor infantil",
        urlImages: "./images/juego-comedor-infantil.jpg",
        stock:10,
        price:350,
    },
    {
        id:9,
        name:"escritorio",
        urlImages: "./images/escritorio.jpg",
        stock:8,
        price:1.500,
    }
]
